### ISSUE TITLE
Systems integration and final demonstration

### ISSUE THREAD

**Issue by devangel77b** [usna-ew309/corona#11]
From @tracieseverson:
6.  System Integration/Final Demonstration - need a way to incorporate all of the above together.  

Mike - I think you are working to incorporate the computer vision portion into the whole she-bang for the system integration?  I believe we need to be able to simulate what the camera sees so that the students can use their existing computer vision code to find the correct target and compute a centroid?  Could we also use video if necessary and have them parse each image to run their code?  Maybe that's not the best way.    

I'm envisioning the centroid from their computer vision code as the theta_desired to kick off the closed-loop turret model that Levi is working on.

Tracie - gather necessary date for turret model, update all the ballistics slides/information to match what we are going to do for this semester without physical weapons, update guidance on test plan development.

**Comment by devangel77b** [comment]
4.  System Integration - Mike and Levi I think?  Possible Dennis and Tracie
  a.  Still farther down the road - I believe it is going to be a combination of Mike and Levi with the computer vision and simulation control code.  Oh and the ballistics so Dennis is in there as well and I can do the slides and guidance.

**Comment by devangel77b** [comment]
5.  Final Demonstration - Tracie
  a.  Once we know how the system integration is going to proceed, I will modify the current final demonstration handout to reflect how we are going to proceed.  I envision a process by where the students send us their final code and we run it through the simulation model  OR it might be kinda neat to set up individual times on Zoom or another means to "run" their final demonstration while they share their screens with us so we can watch their results.  It makes is more personal and kinda more like a final demo.  Let's chew on this one a bit more...

**Comment by kutzer** [comment]
Hi Guys:

This is how I envision the final demonstration (and student testing prior to) flowing:
1. Define target information 
    - targetSpecs = createTargetSpecs
2. Define test range 
    - range = VALUE IN CENTIMETERS
3. Get image of target at random angle between -25deg & 25deg
    - im = getTargetImage(500,[],targetSpecs);
4. Process the image and range to get
    - theta_desired % in radians
    - nShots
5. Define control parameters
    - cParams.Kp = Kp; % student defined
    - cParams.Ki  = Ki; % student defined
    - cParams.Kd = Kd; % student defined
    - cParams.despos = theta_desired % in radians
6. Define stop condition (e.g. evaluation time)
    - tf = VALUE % in seconds, student defined
    - t = linspace(0,tf,100); % this can change
7. Run the turret model
    - [SSE,tOUT,theta,omega,duty_cycle,eint] = sendCmdtoDcMotor('closed',cParams,t);
8. Print steady state error
    - fprintf('SSE = %.7f\n',SSE);
9. Get image of target after turret is moved
    - im = getTargetImageUpdate(theta(end));
10. Repeat steps 2 - 9 as desired
11. Fire at target
    - im = getShotPatternImage(nShots);

**Comment by kutzer** [comment]
12. Instructors can assess performance visually using
- EW309coronaPerforanceEval

**Comment by kutzer** [comment]
Kutzer pushed final demonstration skeleton code to git.
