### ISSUE TITLE
Update README to provide how to git

### ISSUE THREAD

**Issue by devangel77b** [usna-ew309/corona#17]
Needs git / github instructions for use under windows Github GUI interface.

**Comment by devangel77b** [comment]
Mike got help figuring out git-lfs to track some large movies and mats

**Comment by devangel77b** [comment]
Mike helped Tracie to get github installed and working

**Comment by kutzer** [comment]
# Install procedure for git:
1. Use git to fetch the latest version of EW309\corona
1. Open MATLAB as an administrator
1. Change your MATLAB directory to ...\GitHub\corona
1. Run "installEW309corona" from the command window

# Install procedure when downloading the *.zip
1. Download corona-master.zip (https://github.com/usna-ew309/corona/archive/master.zip)
1. Open MATLAB as an administrator
1. Unzip/Extract corona-master.zip
1. Change your MATLAB directory to ...\corona-master\corona-master\support
1. Run "EW309coronaUpdate" from the command window
1. Allow the installation to complete

**Comment by kutzer** [comment]
Review SCRIPT_PackageTest_EW309Corona.m for current function usage examples.

**Comment by kutzer** [comment]
# Install procedure with single file
1. Provide students with a stable copy of "EW309coronaUpdate.m"
1. Open MATLAB as an administrator
1. Change your MATLAB directory to the location of "EW309coronaUpdate.m"
1. Run "EW309coronaUpdate" from the command window
1. Allow the installation to complete

**Comment by kutzer** [comment]
# REVISED install procedure with *two* files
1. Provide students with a stable copy of "installSupportToolboxes.m" *and* "EW309coronaUpdate.m"
1. Open MATLAB as an administrator
1. Change your MATLAB directory to the location of"installSupportToolboxes.m" *and* "EW309coronaUpdate.m"
1. Run "installSupportToolboxes" from the command window
1. Allow the installation to complete
1. Run "EW309coronaUpdate" from the command window
1. Allow the installation to complete

**Comment by devangel77b** [comment]
Added these to readme and updated version number to 1.2.0 in the tags etc.

**Comment by devangel77b** [comment]
Edited to include 3 file guidance from !! READ ME.txt in Gogole Drive (from K).

**Comment by devangel77b** [comment]
Install tested on all of M W 1 and 3 sections.
