### ISSUE TITLE
Hersom seeing errors on running EW309coronaUpdate?

### ISSUE THREAD

**Issue by devangel77b** [usna-ew309/corona#27]
I haven't tried to recreate these myself yet... (may already be fixed by v1.2.7 and guys haven't updated yet). 

Professor,
These are the errors that I'm getting:
```
Undefined function or variable 'initCameraSim'.
Error in create3Dfov (line 58)
    sim = initCameraSim(A_c2m,imageResolution,0.5*24*12*25.4);
Error in gitlfsFixEW309corona (line 102)
create3Dfov
Error in EW309coronaUpdate (line 53)
gitlfsFixEW309corona;
```

**Comment by kutzer** [comment]
The issue is tied to the midshipmen not following the proper installation instructions:
1. Close all instances of MATLAB
2. Open MATLAB as an administrator
3. Run installSupportPackages
4. Run EW309coronaUpdate

These midshipmen skipped step (3).
