### ISSUE TITLE
Work on ballistics simulator 

### ISSUE THREAD

**Issue by devangel77b** [usna-ew309/corona#6]
Work on code like the 202 random variables lab where they can simulate ballistics shots - either using a stats model or a physics based model with some stochastic bits; then they fit CEP and drop and stuff to it. 

Since I haven't done this part of lab before I will review AY19 and the old data too.

**Comment by devangel77b** [comment]
From @tracieseverson: 
5.  Ballistics Analysis - sounds like Dennis is working on this?  I think we need to either give the students data (range and points of impact for a variety of ranges) or some ballistics model that they can use to take a certain number of shots at different ranges and get the impact points to compute their weapon's ballistics profile.

Dennis - can you work on the ballistics piece (I think you already are).  We should also have them develop a test plan before we give them any data or the model.  I have an example I will put in the Google Drive.  I also have the ballistics slides from last year I will update and post.

**Comment by devangel77b** [comment]
From @kutzer:
For the ballistics functions, we need the following:
A mean and covariance of the shot pattern for a handful of distances.
A function to calculate mean and covariance as a function of distance I do the first part of this in my SCRIPT_BallisticsAnalysis.m code by fitting a polynomial to:
The x-mean
The y-mean
The square root of the eigenvalues of the covariance
The "angle" of the covariance 
Can someone take this and run with it?

**Comment by devangel77b** [comment]
3.  Ballistics Analysis -- Dennis and Tracie
   a.  QUESTION - Collect new ballistics data or use what is in the google drive?  
 The data I have in their now is a combination of old data and data taken from last year.  I thought Dennis said he might be able to collect new data?  It is not mandatory for next week by any means but since we seem to be a forward-looking team

   b. Last year's slides are in the google drive.  Most of them can be used again I think - just need to update based on data we collect.  I'm happy to update slides if someone can tell me what data we are going to use?

**Comment by devangel77b** [comment]
My thoughts: 
3a. Let's just use what ballistics data we have (or can simulate); if we decide we need more I can retake but it would take longer than just popping into the room with a tape measure or camera; we'd have to set up the whole camera and firing circuit. 
3b. I didn't see slides but maybe I am looking in the wrong place? I only saw the data (or are we looking in AY19)?

**Comment by devriesusna** [comment]
Dennis, where are we at on this?

**Comment by tracieseverson** [comment]
I will upload the ballistics function later this week/weekend.  I think I already have this code developed.
