### ISSUE TITLE
Turret system modeling

### ISSUE THREAD

**Issue by devangel77b** [usna-ew309/corona#8]
Turret System Modeling - students should develop a simple model of their auto-turret based on their data (encoder counts vs time).  If they didn't get to that section, we should provide them this data (similar to what I was collecting yesterday for Mike).  We would need to give them data for the turret turning in both directions.

**Comment by devangel77b** [comment]
Tracie - gather necessary date for turret model, update all the ballistics slides/information to match what we are going to do for this semester without physical weapons, update guidance on test plan development.

**Comment by devangel77b** [comment]
From @kutzer Hi Levi:

I would say let's take the path of least resistance. Take a look at my code from last year:

 10. Turret System Modeling

Basically, I'm already generating simulated data for the turret!! All we need to do is make it realistic given the data that Tracie has collected.

- Mike

**Comment by devangel77b** [comment]
https://drive.google.com/drive/u/1/folders/1XhTVFVaF1eS-THloI5QchOkYitLU0k04

**Comment by devriesusna** [comment]
Added a very simple model with nonlinear input dead zone and nonlinear friction. Friction is just a saturation function right now. It might be good enough for our needs.

**Comment by devangel77b** [comment]
1.  Turret System Modeling - Tracie 
       a.  Either modify the current slides or create a smaller slide deck specific to the current situation (basically have them download the Step Data and analyze).  

       QUESTION - the tfest works great in positive direction but not in the negative direction.  Levi and I worked on this and he came up with a good solution to use fmincon.  He ran the negative data a few times with different initial guesses and his response is below:

     After running fmincon a few times with different initial guesses, it looks like the solution is somewhat sensitive around the answer H(s) = a/s^2 for some number a. If      you guess an unstable initial transfer function $H(s) = a/((s+b)*(s-c))$ for positive b and c, then try again with a stable guess  $H(s) = a/((s+b)*(s+c))$ for positive b and c, it finds completely different answers (one stable, one unstable). Maybe this is why TFest struggles?

       POSSIBLE SOLUTIONS - (1) only use the data in the positive direction and tfest works great; (2) use the data in both directions and use fmincon.  Either way we will have to give them the shell of the code to execute the analysis.

**Comment by devriesusna** [comment]
I updated the slides. I think this one is good to go? If no objections, I'm going to close this issue.
